name: checkov
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Scan with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          download_external_modules: false
          output_format: cli,sarif
          output_file_path: console,results.sarif
          skip_path: examples
